// src/services/scanner/types.ts
// ═══════════════════════════════════════════════════════════════════════════
// Scanner Types - Automated scanning system type definitions
// ═══════════════════════════════════════════════════════════════════════════

export interface SearchQuery {
  /** The search term to use */
  query: string;
  /** Category or type of search (for logging/stats) */
  category: 'graded' | 'wotc' | 'vintage' | 'modern' | 'chase' | 'dynamic-recent' | 'general' | 'catchall' | 'custom';
  /** Weight for rotation (higher = more frequent) */
  weight: number;
  /** Whether this query is currently enabled */
  enabled: boolean;
  /** Optional metadata for dynamic queries */
  meta?: {
    expansionId?: string;
    releaseDate?: string;
    isAutoGenerated?: boolean;
    isUserDefined?: boolean;
  };
}

/** Search type: 'dynamic' uses built-in weighted queries, 'custom' uses user-defined terms, 'recent' fetches newest listings */
export type SearchType = 'dynamic' | 'custom' | 'recent';

/** Custom search term as stored in user preferences */
export interface CustomSearchTerm {
  /** The search term/query string */
  term: string;
  /** Weight for rotation (1-5, higher = more frequent) */
  weight: number;
  /** Whether this term is enabled */
  enabled: boolean;
}

export interface ScanResult {
  /** Query that was executed */
  query: string;
  /** Number of eBay listings fetched */
  listingsFetched: number;
  /** Number of listings processed */
  listingsProcessed: number;
  /** Number of cards successfully matched in Scrydex */
  cardsMatched: number;
  /** Number of new deals found */
  dealsFound: number;
  /** API credits consumed */
  creditsUsed: number;
  /** Time taken in milliseconds */
  durationMs: number;
  /** Timestamp of scan completion */
  completedAt: Date;
  /** Any errors that occurred */
  errors: string[];
}

export type ScannerMode = 'both' | 'graded' | 'raw';

export interface ScannerStats {
  /** Whether the scanner is currently running */
  isRunning: boolean;
  /** Current status message */
  status: string;
  /** Scanner mode - what types of cards to scan for */
  scannerMode: ScannerMode;
  /** Search type - 'dynamic' for built-in queries, 'custom' for user-defined */
  searchType: SearchType;
  /** Total scans completed today */
  scansToday: number;
  /** Total credits used today */
  creditsToday: number;
  /** Daily credit budget */
  dailyBudget: number;
  /** Credits remaining in daily budget */
  creditsRemaining: number;
  /** Current query being used */
  currentQuery: string | null;
  /** Index in the query rotation */
  rotationIndex: number;
  /** Total queries in rotation (static + dynamic + custom) */
  totalQueries: number;
  /** Number of static queries */
  staticQueries: number;
  /** Number of dynamic queries (auto-generated from recent releases) */
  dynamicQueries: number;
  /** Number of custom queries (user-defined) */
  customQueries: number;
  /** Timestamp of last scan */
  lastScanAt: Date | null;
  /** Timestamp of next scheduled scan */
  nextScanAt: Date | null;
  /** Calculated interval between scans (minutes) */
  scanIntervalMinutes: number;
  /** Total deals found today */
  dealsFoundToday: number;
  /** Date of current stats (resets daily) */
  statsDate: string;
  /** Last time dynamic queries were refreshed */
  lastDynamicRefresh: Date | null;
  /** Monthly credits used (from API) */
  monthlyCreditsUsed?: number;
  /** Monthly credits remaining */
  monthlyCreditsRemaining?: number;
  /** Monthly credit limit */
  monthlyLimit?: number;
  /** Days remaining in billing period */
  billingDaysRemaining?: number;
  /** eBay API rate limit status */
  ebayRateLimited?: boolean;
  /** Time until rate limit resets (ms) */
  ebayRateLimitRetryAfterMs?: number;
  /** Full eBay rate limit data (for UI display) */
  ebayRateLimits?: {
    isLimited: boolean;
    retryAfterMs: number;
    consecutiveHits: number;
    remaining?: number;
    limit?: number;
    count?: number;
    resetAt?: string;
    timeWindowSeconds?: number;
  };
}

export interface ScannerConfig {
  /** Scanner mode - what types of cards to scan for */
  scannerMode: ScannerMode;
  /** Search type - 'dynamic' for built-in queries, 'custom' for user-defined */
  searchType: SearchType;
  /** Maximum credits to use per day */
  dailyCreditBudget: number;
  /** Minimum interval between scans (minutes) */
  minScanIntervalMinutes: number;
  /** Maximum interval between scans (minutes) */
  maxScanIntervalMinutes: number;
  /** Number of listings to fetch per scan */
  listingsPerScan: number;
  /** Hours of the day to operate (24h format) */
  operatingHours: {
    start: number;
    end: number;
  };
  /** Whether to auto-start on server boot */
  autoStart: boolean;
  /** Deal expiration time in hours */
  dealExpirationHours: number;
  /** Estimated credits per scan (for interval calculation) */
  estimatedCreditsPerScan?: number;
  /** How often to refresh dynamic queries (hours) */
  dynamicQueryRefreshHours?: number;
  /** Custom search terms (only used when searchType is 'custom') */
  customSearchTerms?: CustomSearchTerm[];
}

export interface DailyStats {
  date: string;
  scansCompleted: number;
  creditsUsed: number;
  dealsFound: number;
  listingsProcessed: number;
  errors: number;
}